"""
Static database of jewelry/auction platforms with known metadata.
monthly_visits_est: approximate monthly visits (publicly known data, updated 2024-2025)
"""

PLATFORMS = [
    {
        "name": "Catawiki",
        "url": "https://www.catawiki.com",
        "domain": "catawiki.com",
        "category": "מכרזים",
        "specialty": "מכרזים אוצנים – תכשיטים, אמנות, אספנות",
        "jewelry_focus": 5,
        "seller_fees": "12.5% עמלת מוכר",
        "buyer_fees": "9% פרמיה",
        "regions": ["אירופה", "עולמי"],
        "languages": ["אנגלית", "עברית", "הולנדית", "צרפתית", "+20"],
        "notes": "נקודת ייחוס – האתר שממנו מתחיל החיפוש",
        "color": "#FF6B35",
        "monthly_visits_est": "25M",
    },
    {
        "name": "eBay",
        "url": "https://www.ebay.com",
        "domain": "ebay.com",
        "category": "מרקטפלייס + מכרזים",
        "specialty": "הכל כולל תכשיטים, מכרזים ומחיר קבוע",
        "jewelry_focus": 4,
        "seller_fees": "6.35%–15% לפי קטגוריה",
        "buyer_fees": "ללא",
        "regions": ["עולמי"],
        "languages": ["אנגלית", "+20"],
        "notes": "הכי גדול בעולם, תחרות גבוהה, חשיפה עצומה",
        "color": "#E53238",
        "monthly_visits_est": "600M",
    },
    {
        "name": "Etsy",
        "url": "https://www.etsy.com",
        "domain": "etsy.com",
        "category": "מרקטפלייס יד-עשייה",
        "specialty": "תכשיטים בעבודת יד, וינטג', עיצוב אישי",
        "jewelry_focus": 5,
        "seller_fees": "6.5% + $0.20 לרישום",
        "buyer_fees": "ללא",
        "regions": ["עולמי"],
        "languages": ["אנגלית", "+10"],
        "notes": "אידיאלי לתכשיטים אומנותיים, קהל מאוד ממוקד",
        "color": "#F56400",
        "monthly_visits_est": "400M",
    },
    {
        "name": "1stDibs",
        "url": "https://www.1stdibs.com",
        "domain": "1stdibs.com",
        "category": "יוקרה",
        "specialty": "תכשיטים יוקרתיים, אנטיק, אמנות",
        "jewelry_focus": 5,
        "seller_fees": "~$500/חודש + 20% עמלה",
        "buyer_fees": "ללא",
        "regions": ["צפון אמריקה", "אירופה"],
        "languages": ["אנגלית"],
        "notes": "פלטפורמת יוקרה מובילה, דורשת אישור מוכר",
        "color": "#1a1a1a",
        "monthly_visits_est": "7M",
    },
    {
        "name": "Invaluable",
        "url": "https://www.invaluable.com",
        "domain": "invaluable.com",
        "category": "מכרזים",
        "specialty": "מכרזים של בתי מכירות, תכשיטים ואמנות",
        "jewelry_focus": 4,
        "seller_fees": "תלוי בית מכירות",
        "buyer_fees": "15%–25% פרמיה",
        "regions": ["עולמי"],
        "languages": ["אנגלית"],
        "notes": "מאגד מאות בתי מכירות, חשיפה גבוהה",
        "color": "#8B1A1A",
        "monthly_visits_est": "3M",
    },
    {
        "name": "LiveAuctioneers",
        "url": "https://www.liveauctioneers.com",
        "domain": "liveauctioneers.com",
        "category": "מכרזים",
        "specialty": "מכרזים בזמן אמת – תכשיטים, אנטיק",
        "jewelry_focus": 4,
        "seller_fees": "3%–5% דמי פלטפורמה",
        "buyer_fees": "25%–30% פרמיה",
        "regions": ["עולמי"],
        "languages": ["אנגלית"],
        "notes": "מכרזים חיים בזמן אמת, מאוד פופולרי בארה\"ב",
        "color": "#2E4057",
        "monthly_visits_est": "4M",
    },
    {
        "name": "The RealReal",
        "url": "https://www.therealreal.com",
        "domain": "therealreal.com",
        "category": "יד שנייה יוקרה",
        "specialty": "תכשיטים ואקססוריז יוקרה מאומתים",
        "jewelry_focus": 4,
        "seller_fees": "15%–30% עמלה",
        "buyer_fees": "ללא",
        "regions": ["ארה\"ב"],
        "languages": ["אנגלית"],
        "notes": "אימות מקצועי, ממוקד בלוקסורי מאוחד",
        "color": "#4A2040",
        "monthly_visits_est": "10M",
    },
    {
        "name": "Vestiaire Collective",
        "url": "https://www.vestiairecollective.com",
        "domain": "vestiairecollective.com",
        "category": "יד שנייה יוקרה",
        "specialty": "אופנה ותכשיטים יוקרתיים",
        "jewelry_focus": 3,
        "seller_fees": "12%–22% עמלה",
        "buyer_fees": "ללא",
        "regions": ["אירופה", "עולמי"],
        "languages": ["צרפתית", "אנגלית", "+10"],
        "notes": "חזק באירופה, אימות על פריטי יוקרה",
        "color": "#006241",
        "monthly_visits_est": "15M",
    },
    {
        "name": "Ruby Lane",
        "url": "https://www.rubylane.com",
        "domain": "rubylane.com",
        "category": "אנטיק ווינטג'",
        "specialty": "תכשיטים אנטיקים ווינטג'",
        "jewelry_focus": 5,
        "seller_fees": "$25/חודש + 9.9%",
        "buyer_fees": "ללא",
        "regions": ["ארה\"ב", "בינלאומי"],
        "languages": ["אנגלית"],
        "notes": "מומחה בתכשיטים אנטיקים, קהל נישה מאוד ממוקד",
        "color": "#8B0000",
        "monthly_visits_est": "1M",
    },
    {
        "name": "Worthy",
        "url": "https://www.worthy.com",
        "domain": "worthy.com",
        "category": "מכרזים לתכשיטים",
        "specialty": "תכשיטים בלבד – יהלומים, טבעות",
        "jewelry_focus": 5,
        "seller_fees": "14%–18% עמלה",
        "buyer_fees": "ללא",
        "regions": ["ארה\"ב"],
        "languages": ["אנגלית"],
        "notes": "מתמחה אך ורק בתכשיטים יקרי ערך, שמאות חינם",
        "color": "#D4AF37",
        "monthly_visits_est": "500K",
    },
    {
        "name": "Bonhams",
        "url": "https://www.bonhams.com",
        "domain": "bonhams.com",
        "category": "בית מכירות",
        "specialty": "מכרזי יוקרה – תכשיטים, שעונים, אמנות",
        "jewelry_focus": 4,
        "seller_fees": "0%–10% עמלת מוכר",
        "buyer_fees": "25%–27.5% פרמיה",
        "regions": ["עולמי"],
        "languages": ["אנגלית"],
        "notes": "בית מכירות יוקרתי מוכר עם נוכחות עולמית",
        "color": "#2C3E50",
        "monthly_visits_est": "1.5M",
    },
    {
        "name": "Everything But The House",
        "url": "https://www.ebth.com",
        "domain": "ebth.com",
        "category": "מכרזים",
        "specialty": "מכרזים לפריטי בית, תכשיטים, אמנות",
        "jewelry_focus": 3,
        "seller_fees": "ללא (EBTH מנהל הכל)",
        "buyer_fees": "15% פרמיה",
        "regions": ["ארה\"ב"],
        "languages": ["אנגלית"],
        "notes": "מודל ייחודי – הם מצלמים ומנהלים, מתאים לאוספים",
        "color": "#27AE60",
        "monthly_visits_est": "600K",
    },
    {
        "name": "Poshmark",
        "url": "https://www.poshmark.com",
        "domain": "poshmark.com",
        "category": "מרקטפלייס יד שנייה",
        "specialty": "אופנה ותכשיטים יד שנייה",
        "jewelry_focus": 3,
        "seller_fees": "$2.95 מתחת ל-$15, 20% מעל",
        "buyer_fees": "ללא",
        "regions": ["ארה\"ב", "קנדה", "אוסטרליה"],
        "languages": ["אנגלית"],
        "notes": "פופולרי בארה\"ב, קהל צעיר, מהיר ופשוט",
        "color": "#FF2D55",
        "monthly_visits_est": "50M",
    },
    {
        "name": "Barnebys",
        "url": "https://www.barnebys.com",
        "domain": "barnebys.com",
        "category": "אגרגטור מכרזים",
        "specialty": "חיפוש מכרזים – תכשיטים, אמנות, אנטיק",
        "jewelry_focus": 4,
        "seller_fees": "ללא (אגרגטור)",
        "buyer_fees": "לפי בית המכירות",
        "regions": ["אירופה", "עולמי"],
        "languages": ["אנגלית", "שוודית", "גרמנית", "+5"],
        "notes": "מנוע חיפוש למכרזים, לא מוכרים ישירות אבל חשיפה טובה",
        "color": "#3498DB",
        "monthly_visits_est": "2M",
    },
    {
        "name": "Chrono24",
        "url": "https://www.chrono24.com",
        "domain": "chrono24.com",
        "category": "שעונים",
        "specialty": "שעונים יוקרתיים (רלוונטי לתכשיטים עם שעונים)",
        "jewelry_focus": 2,
        "seller_fees": "6.5% עמלה",
        "buyer_fees": "ללא",
        "regions": ["עולמי"],
        "languages": ["אנגלית", "גרמנית", "+10"],
        "notes": "המוביל בשעונים, פחות רלוונטי לתכשיטים בלבד",
        "color": "#1ABC9C",
        "monthly_visits_est": "15M",
    },
]
